name = "protecc-ur-bagz"
compatibility_date = "2022-05-03"
main = "index.js"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.dev.durable_objects]
bindings = [
    {name = "COUNTER", class_name = "Counter"},
    {name = "TRAILING_STOP_LOSS_OPEN_ORDERS", class_name = "TrailingStopLossOpenOrders" }
]
