name = "protecc-ur-bagz"
compatibility_date = "2022-05-03"
main = "index.js"

[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"

[[migrations]]
tag = "v1" # Should be unique for each entry

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.dev.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" }
]
