name = "protecc-ur-bagz"
compatibility_date = "2022-05-03"
main = "index.ts"
compatibility_flags = [ "nodejs_compat" ]


[[migrations]]
tag = "v1" # Should be unique for each entry

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.dev.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" },
    {name = "TokenPairPositionTrackerDO", class_name = "TokenPairPositionTrackerDO" },
    {name = "PolledTokenPairListDO", class_name = "PolledTokenPairListDO" },
    {name = "BetaInviteCodesDO", class_name = "BetaInviteCodesDO" }
]

# The 'wake up!' cron trigger
[triggers]
crons = [ "* * * * *" ]
