name = "protecc-ur-bagz"
compatibility_date = "2022-05-03"
main = "index.ts"
logpush = true
compatibility_flags = [ "nodejs_compat" ]


[[migrations]]
tag = "v1" # Should be unique for each entry

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.beta]
vars = { ENVIRONMENT = "beta" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.prod]
vars = { ENVIRONMENT = "prod" }

[env.dev.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" },
    {name = "TokenPairPositionTrackerDO", class_name = "TokenPairPositionTrackerDO" },
    {name = "PolledTokenPairListDO", class_name = "PolledTokenPairListDO" },
    {name = "BetaInviteCodesDO", class_name = "BetaInviteCodesDO" },
    {name = "HeartbeatDO", class_name = "HeartbeatDO" }
]

[env.beta.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" },
    {name = "TokenPairPositionTrackerDO", class_name = "TokenPairPositionTrackerDO" },
    {name = "PolledTokenPairListDO", class_name = "PolledTokenPairListDO" },
    {name = "BetaInviteCodesDO", class_name = "BetaInviteCodesDO" },
    {name = "HeartbeatDO", class_name = "HeartbeatDO" }
]

[env.staging.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" },
    {name = "TokenPairPositionTrackerDO", class_name = "TokenPairPositionTrackerDO" },
    {name = "PolledTokenPairListDO", class_name = "PolledTokenPairListDO" },
    {name = "BetaInviteCodesDO", class_name = "BetaInviteCodesDO" },
    {name = "HeartbeatDO", class_name = "HeartbeatDO" }
]

[env.prod.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" },
    {name = "TokenPairPositionTrackerDO", class_name = "TokenPairPositionTrackerDO" },
    {name = "PolledTokenPairListDO", class_name = "PolledTokenPairListDO" },
    {name = "BetaInviteCodesDO", class_name = "BetaInviteCodesDO" },
    {name = "HeartbeatDO", class_name = "HeartbeatDO" }
]


# The 'wake up!' cron trigger - keeps the price tracker tracking the prices.
[triggers]
crons = [ "* * * * *" ]
